// import type { Product } from "../../types/Product/producttypeAdmin";

// export const productsData: Product[] = [
//     // 1. DSLR Camera Tripod
//     {
//         id: 1,
//         title: "Professional DSLR Camera Tripod",
//         description: "Heavy-duty aluminum tripod with 360° pan head, quick-release plate, and 15 lb payload capacity.",
//         price: 129.99,
//         original_price: 179.99,
//         rating: 4.6,
//         is_new: false,
//         is_featured: true,
//         is_active: true,
//         reviews_count: 532,
//         instock: 0,
//         delivery_fee: "5",
//         images: [
//             { id: 1, url: "https://images-cdn.ubuy.co.id/68381354ecd281cdcd0d216d-canon-eos-rebel-t7-dslr-camera-with.jpg", is_primary: true },
//             { id: 2, url: "https://i5.walmartimages.com/asr/a5ca1818-6b35-4b9f-b666-c22515d86e8f.326e2e733c12af9cdb93e19f0de363d4.jpeg", is_primary: false },
//         ],
//         hover_image: "https://i5.walmartimages.com/asr/a5ca1818-6b35-4b9f-b666-c22515d86e8f.326e2e733c12af9cdb93e19f0de363d4.jpeg",
//         tags: ["tripod", "camera", "stability"],
//         colors: [{ name: "Black", hex: "#000000", stock: 10 }],
//         features: ["360° Pan Head", "Quick-Release", "15 lb Payload"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 1,
//         category: { id: 1, name: "Photography" },
//         // brand: "ProStabil"
//     },
//     // 2. 4K Short-Throw Projector
//     {
//         id: 2,
//         title: "4K Short-Throw Projector",
//         description: "Capture big-screen entertainment even in tight spaces with crystal-clear 4K projection and 3200 ANSI lumen brightness.",
//         price: 999.99,
//         original_price: 1299.99,
//         rating: 4.7,
//         is_new: true,
//         is_featured: false,
//         is_active: true,
//         reviews_count: 845,
//         instock: 15,
//         delivery_fee: "20",
//         images: [
//             { id: 3, url: "https://www.optomaeurope.com/ContentStorage/Media/ad83897c-763a-4f36-ad2e-8ed751ba601e.jpg", is_primary: true },
//             { id: 4, url: "https://www.eliteprojector.com/wp-content/uploads/EP_MGFU_Distance_60_100_120.jpg", is_primary: false },
//         ],
//         hover_image: "https://i.ytimg.com/vi/OuEqXqAyq2g/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDTK0nICL-NCiM9F9YfesEdXYUSzA",
//         tags: ["projector", "4K", "short-throw"],
//         colors: [{ name: "White", hex: "#FFFFFF", stock: 15 }],
//         features: ["4K HDR", "3200 lm Brightness", "Short-Throw Lens"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 2,
//         category: { id: 2, name: "Projectors" },
//         // brand: "VisionWide"
//     },
//     // 3. Ultra Portable Mini Projector
//     {
//         id: 3,
//         title: "Portable Mini Projector",
//         description: "Compact, budget-friendly projector with Wi-Fi, Bluetooth, and app streaming—perfect for on-the-go viewing.",
//         price: 199.99,
//         original_price: 249.99,
//         rating: 4.2,
//         is_new: true,
//         is_featured: true,
//         is_active: true,
//         reviews_count: 1270,
//         instock: 60,
//         delivery_fee: "0",
//         images: [
//             { id: 5, url: "https://m.media-amazon.com/images/I/71tw5u0VXAL._UF350,350_QL80_.jpg", is_primary: true },
//             { id: 6, url: "https://m.media-amazon.com/images/I/71UwGm5juyL._UF1000,1000_QL80_.jpg", is_primary: false },
//         ],
//         hover_image: "https://m.media-amazon.com/images/I/71fsuvWlZYL._UF1000,1000_QL80_.jpg",
//         tags: ["mini", "portable", "streaming"],
//         colors: [{ name: "Gray", hex: "#6B7280", stock: 60 }],
//         features: ["Wi-Fi", "Bluetooth", "Portable"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 2,
//         category: { id: 2, name: "Projectors" },
//         // brand: "PocketCinema"
//     },
//     // 4. Gaming Laptop with RTX
//     {
//         id: 4,
//         title: "Gaming Laptop RTX 4070",
//         description: "Powerhouse 15.6″ laptop with RTX 4070, 16GB RAM, 1TB SSD, and 240 Hz refresh rate for uncompromised gameplay.",
//         price: 1899.99,
//         original_price: 2199.99,
//         rating: 4.9,
//         is_new: true,
//         is_featured: true,
//         is_active: true,
//         reviews_count: 977,
//         instock: 30,
//         delivery_fee: "15",
//         images: [
//             { id: 7, url: "https://cdn.mos.cms.futurecdn.net/WWyc6ANwtvYpYPtNqL9fxD.jpg", is_primary: false },
//             { id: 8, url: "https://m.media-amazon.com/images/I/71KESlYGP-L._UF894,1000_QL80_.jpg", is_primary: true },
//         ],
//         hover_image: "https://img.overclockers.co.uk/images/LT-0EU-GI/8486164db193a66198a702fb1aab42af.jpg",
//         tags: ["gaming", "laptop", "RTX4070"],
//         colors: [
//             { name: "Black", hex: "#000000", stock: 20 },
//             { name: "Red", hex: "#DC2626", stock: 10 },
//         ],
//         features: ["RTX 4070", "240 Hz Display", "1TB SSD"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 3,
//         category: { id: 3, name: "Computers" },
//         // brand: "GameCore"
//     },
//     // 5. Flagship Smartphone
//     {
//         id: 5,
//         title: "Flagship Smartphone Pro",
//         description: "Cutting-edge smartphone with 120 Hz AMOLED display, triple-lens 108 MP camera, 5G, and 5000 mAh battery.",
//         price: 999.99,
//         original_price: 1099.99,
//         rating: 4.8,
//         is_new: true,
//         is_featured: true,
//         is_active: true,
//         reviews_count: 3245,
//         instock: 100,
//         delivery_fee: "0",
//         images: [
//             { id: 9, url: "https://images-cdn.ubuy.co.nl/675cac98104094089601b6d2-meet-the-pinephone-pro-our-flagship.jpg", is_primary: false },
//             { id: 10, url: "https://static1.xdaimages.com/wordpress/wp-content/uploads/2021/10/pinephone-pro-feature-image.jpg", is_primary: true },
//         ],
//         hover_image: "https://cdn.arstechnica.net/wp-content/uploads/2022/01/2-2.jpg",
//         tags: ["smartphone", "5G", "camera"],
//         colors: [
//             { name: "Graphite", hex: "#1F2937", stock: 60 },
//             { name: "Silver", hex: "#E5E7EB", stock: 40 },
//         ],
//         features: ["108 MP Camera", "120 Hz AMOLED", "5G Support"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 4,
//         category: { id: 4, name: "Phones" },
//         // brand: "Zenith"
//     },
//     // 6. Content Creator Convertible Laptop
//     {
//         id: 6,
//         title: "2-in-1 Convertible Laptop",
//         description: "Ultra-light touchscreen laptop with Intel i7, 16GB RAM, 512GB SSD, and stylus support for creators on the go.",
//         price: 1299.99,
//         original_price: 1499.99,
//         rating: 4.5,
//         is_new: false,
//         is_featured: false,
//         is_active: true,
//         reviews_count: 430,
//         instock: 45,
//         delivery_fee: "10",
//         images: [
//             { id: 11, url: "https://i.rtings.com/assets/pages/MQFiUURx/best-2-in-1-laptops-20240516-medium.jpg?format=auto", is_primary: true },
//             { id: 12, url: "https://images.bauerhosting.com/affiliates/sites/8/2024/06/Untitled-1.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=1440&q=80", is_primary: false },
//         ],
//         hover_image: "https://m.media-amazon.com/images/I/71Etuz5e4-L.jpg",
//         tags: ["2-in-1", "laptop", "touchscreen"],
//         colors: [
//             { name: "Silver", hex: "#D1D5DB", stock: 25 },
//             { name: "Space Gray", hex: "#4B5563", stock: 20 },
//         ],
//         features: ["Touchscreen", "Stylus", "Intel i7", "512 GB SSD"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 3,
//         category: { id: 3, name: "Computers" },
//         // brand: "CreateFlex"
//     },
//     // 7. Mirrorless Camera Kit
//     {
//         id: 7,
//         title: "Mirrorless Camera Kit",
//         description: "Professional mirrorless camera with 24.2MP sensor, 4K video recording, and bundled with a 28-70mm lens.",
//         price: 1599.99,
//         original_price: 1799.99,
//         rating: 4.8,
//         is_new: true,
//         is_featured: false,
//         is_active: true,
//         reviews_count: 810,
//         instock: 25,
//         delivery_fee: "15",
//         images: [
//             { id: 13, url: "https://i5.walmartimages.com/seo/Canon-EOS-R50-Mirrorless-Camera-18-45mm-Lens-Bundle-Accessory-Kit-including-128GB-Memory-Backpack-Extra-Battery-Filters-5-2-Video-Photo-Editing-Packa_94c82885-3cf2-48f0-869b-a6ecff57ee76.9b212be4b56809a7c24fe0bdcfda483c.jpeg", is_primary: true },
//             { id: 14, url: "https://i5.walmartimages.com/seo/Canon-EOS-R5-Mirrorless-Camera-Canon-5-2mm-f-2-8-L-Lens-Canon-50mm-1-8-Lens-Backup-Battery-64GB-Kit-Original-Accessories-Included-International-Versi_61cd794e-b516-43f8-8e5b-f9d773448bb5.7b5d1a97fe69674b622bd5625fb87969.jpeg", is_primary: false },
//         ],
//         hover_image: "https://media.sweetwater.com/m/products/image/07f7757099JQcsLJliFcGiQGbP27fA02Qbb9GV5T.wm-lw.jpg?quality=82&width=750&ha=07f7757099fbcc65",
//         tags: ["mirrorless", "camera", "4K"],
//         colors: [{ name: "Black", hex: "#000000", stock: 25 }],
//         features: ["24.2MP Sensor", "4K Video", "Wi-Fi Sharing"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 1,
//         category: { id: 1, name: "Photography" },
//         // brand: "LuminaX"
//     },
//     // 8. Ultra Slim Business Laptop
//     {
//         id: 8,
//         title: "Ultra Slim Business Laptop",
//         description: "Lightweight 14″ business laptop with Intel i5, 8GB RAM, 512GB SSD, and all-day 12h battery life.",
//         price: 1099.99,
//         original_price: 1299.99,
//         rating: 4.4,
//         is_new: false,
//         is_featured: false,
//         is_active: true,
//         reviews_count: 610,
//         instock: 70,
//         delivery_fee: "10",
//         images: [
//             { id: 15, url: "https://m.media-amazon.com/images/I/717vQhiqyxL._UF894,1000_QL80_.jpg", is_primary: true },
//             { id: 16, url: "https://cdn.thewirecutter.com/wp-content/media/2024/07/businesslaptops-2048px-233332.jpg", is_primary: false },
//         ],
//         hover_image: "https://i.pcmag.com/imagery/reviews/04CufB3emFskUertKlTPmdI-1.fit_lim.size_919x518.v1735594586.jpg",
//         tags: ["laptop", "business", "portable"],
//         colors: [
//             { name: "Silver", hex: "#D1D5DB", stock: 40 },
//             { name: "Space Gray", hex: "#4B5563", stock: 30 },
//         ],
//         features: ["Intel i5", "512GB SSD", "12h Battery"],
//         tutorial_video: "https://www.youtube.com/embed/TcpQ4OAKVpQ?si=0SxNy_fQzWyeHlVy&amp;start=48",
//         category_id: 3,
//         category: { id: 3, name: "Computers" },
//         // brand: "BizBook"
//     },
//     // 9. Canon EOS Rebel T7 DSLR Kit
//     {
//         id: 9,
//         title: "Canon EOS Rebel T7 DSLR Kit",
//         description: "Beginner-friendly DSLR camera with 18-55mm lens, built-in Wi-Fi, and 24.1MP sensor for sharp photography.",
//         price: 549.99,
//         original_price: 649.99,
//         rating: 4.7,
//         is_new: false,
//         is_featured: true,
//         is_active: true,
//         reviews_count: 1520,
//         instock: 0,
//         delivery_fee: "10",
//         images: [
//             { id: 17, url: "https://m.media-amazon.com/images/I/714hINuPoBL._AC_SY200_QL15_.jpg", is_primary: false },
//             { id: 18, url: "https://m.media-amazon.com/images/I/71fwaCdTjYL._UF894,1000_QL80_.jpg", is_primary: true }
//         ],
//         hover_image: "https://m.media-amazon.com/images/I/91+V1Hjw6xL._AC_SL1500_.jpg",
//         tags: ["DSLR", "camera", "Wi-Fi"],
//         colors: [{ name: "Black", hex: "#000000", stock: 0 }],
//         features: ["24.1MP", "Wi-Fi", "18-55mm Lens"],
//         tutorial_video: "https://www.youtube.com/embed/FW6g0sH6cK4",
//         category_id: 1,
//         category: { id: 1, name: "Photography" },
//         // brand: "Canon"
//     },
// ]
